package org.huayunaurora.loginAndRegistration.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;
import org.huayunaurora.loginAndRegistration.enums.AccountRoleEnum;
import org.huayunaurora.utils.AccountRoleListConverter;
import org.huayunaurora.utils.AccountStatuesListConverter;
import org.springframework.data.annotation.Id;

import java.io.Serial;
import java.io.Serializable;
import java.util.List;
import java.util.Stack;


@DynamoDBTable(tableName ="account")
@Data
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Account implements Serializable {
    @Serial
    private static final long serialVersionUID = 1L;

    @DynamoDBAttribute(attributeName = "password")
    private String password;

    @DynamoDBAttribute(attributeName = "provider")
    private String provider;

    @Id
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private String Id;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "userNameSearch", attributeName = "user_name")
    private String userName;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "emailSearch", attributeName = "email")
    private String email;

    @DynamoDBAttribute(attributeName = "roles")
    @DynamoDBTypeConverted(converter = AccountRoleListConverter.class)
    private List<AccountRoleEnum> roles;
//pending to design
//    @DynamoDBAttribute(attributeName="account_privilege")
//    private List<AccountPrivilege> accountPrivileges;

    @DynamoDBAttribute(attributeName = "account_statuses")
    @Builder.Default
    @DynamoDBTypeConverted(converter = AccountStatuesListConverter.class)
    private Stack<AccountStatus> accountStatuses = new Stack<>();

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
//    @DynamoDBIndexRangeKey(globalSecondaryIndexName="emailSearch",attributeName="user_name")
    public String getId() {
        return this.Id;

    }

    public void setId(String id) {
        this.Id = id;

    }

}
